import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * 配置侧边栏
 * @see https://docusaurus.io/docs/sidebar
 */
const sidebars: SidebarsConfig = {
    overview: [{ type: 'autogenerated', dirName: 'overview' }],
    tutorials: [{ type: 'autogenerated', dirName: 'tutorials' }],
    others: [{ type: 'autogenerated', dirName: 'others' }],
    meta: [{ type: 'autogenerated', dirName: 'meta' }],
    guide: [{ type: 'autogenerated', dirName: 'documents/quick-start' }],
    software: [{ type: 'autogenerated', dirName: 'documents/software' }],
    hardware: [{ type: 'autogenerated', dirName: 'documents/hardware' }],
    softwaretools: [{ type: 'autogenerated', dirName: 'documents/software-tools' }],
    developertools: [{ type: 'autogenerated', dirName: 'documents/developer-tools' }],
    archivedcontent: [{ type: 'autogenerated', dirName: 'documents/archived-content' }],
};

export default sidebars;
