root: true
env:
  es2020: true
  browser: true
  commonjs: true
overrides:
  - files: '*.ts'
    extends:
      - '@cloudpss'
    env:
      node: true
    rules:
      unicorn/prefer-event-target: 0
  - files:
      - '*.html'
    extends:
      - plugin:@angular-eslint/template/recommended
    rules:
      '@angular-eslint/template/eqeqeq': [1, allowNullOrUndefined: true]
  - files: 'tools/**'
    extends:
      - '@cloudpss'
    env:
      node: true
