root: true
env:
  browser: true
  commonjs: true
overrides:
  - extends:
      - plugin:@angular-eslint/template/recommended
    files:
      - '*.html'
    rules:
      '@angular-eslint/template/eqeqeq': [1, allowNullOrUndefined: true]
