root: true
extends:
  - '@cloudpss'
env:
  es2020: true
  browser: true
  commonjs: true
rules:
  unicorn/prefer-event-target: 0
overrides:
  - files:
      - '*.html'
    extends:
      - plugin:@angular-eslint/template/recommended
    rules:
      '@angular-eslint/template/eqeqeq': [1, allowNullOrUndefined: true]
  - files: 'tools/**'
    env:
      node: true
