debug_mode: false

url: https://docs.cloudpss.net
public_dir: public

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: rsync
  host: 192.168.0.145
  user: root
  root: /root/cloudpssdoc

