ignoredBuiltDependencies:
  - core-js
  - core-js-pure

onlyBuiltDependencies:
  - '@cloudpss/zstd'

publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
  - '*commitlint*'
  - lint-staged

shellEmulator: true
