packages:
  - .
  - tools/docs-to-pdf

ignoredBuiltDependencies:
  - core-js
  - core-js-pure

onlyBuiltDependencies:
  - '@cloudpss/zstd'
  - '@swc/core'
  - puppeteer

publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
  - '*commitlint*'
  - lint-staged

shellEmulator: true
