import MODEL_CLOUDPSS_ACDCHYBRIDCASE from './assets/MODEL_CLOUDPSS_ACDCHYBRIDCASE.webp';
import MODEL_CLOUDPSS_SUBSTATIONCASE from './assets/MODEL_CLOUDPSS_SUBSTATIONCASE.webp';
import MODEL_CLOUDPSS_IEEE39 from './assets/MODEL_CLOUDPSS_IEEE39.webp';
import MODEL_CLOUDPSS_IEEE3 from './assets/MODEL_CLOUDPSS_IEEE3.webp';

const TEMPLATE_PIC_DICT: Record<string, string> = {
    交直流混联系统: MODEL_CLOUDPSS_ACDCHYBRIDCASE,
    '110kV变电站一、二次系统': MODEL_CLOUDPSS_SUBSTATIONCASE,
    '10 机 39 节点标准测试系统': MODEL_CLOUDPSS_IEEE39,
    '3 机 9 节点标准测试系统': MODEL_CLOUDPSS_IEEE3,
    '3 机 9 节点测试系统': MODEL_CLOUDPSS_IEEE3,
};

export { TEMPLATE_PIC_DICT };
