import MODEL_OPEN_CLOUDPSS_SVG_01_AVM_STDM_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_SVG_01-AVM-STDM-V1B1.webp';
import MODEL_OPEN_CLOUDPSS_PCS_BAT_01_AVM_STDM_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_PCS_BAT_01-AVM-STDM-V1B1.webp';
import MODEL_OPEN_CLOUDPSS_PVS_01_AVM_STDM_V1B5 from './assets/MODEL_OPEN-CLOUDPSS_PVS_01-AVM-STDM-V1B5.webp';
import MODEL_OPEN_CLOUDPSS_WTG_DFIG_01_AVM_STDM_V1B5 from './assets/MODEL_OPEN-CLOUDPSS_WTG_DFIG_01-AVM-STDM-V1B5.webp';
import MODEL_OPEN_CLOUDPSS_WTG_PMSG_01_AVM_STDM_V2B5 from './assets/MODEL_OPEN-CLOUDPSS_WTG_PMSG_01-AVM-STDM-V2B5.webp';
import MODEL_CLOUDPSS_IEEE39 from './assets/MODEL_CLOUDPSS_IEEE39.svg?url';
import MODEL_CLOUDPSS_IEEE3 from './assets/MODEL_CLOUDPSS_IEEE3.svg?url';
import MODEL_CLOUDPSS_BLANK_IESMODEL from './assets/MODEL_CLOUDPSS_BLANK_IESMODEL.webp';
import MODEL_CLOUDPSS_BLANK_COMPONENT from './assets/MODEL_CLOUDPSS_BLANK_COMPONENT.webp';
import MODEL_CLOUDPSS_BLANK_COMMON from './assets/MODEL_CLOUDPSS_BLANK_COMMON.webp';
import MODEL_CLOUDPSS_BLANK_SIMPLE from './assets/MODEL_CLOUDPSS_BLANK_SIMPLE.webp';
import MODEL_OPEN_CLOUDPSS_PCS_BAT_01_FDM_STD_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_PCS_BAT_01-FDM-STD-V1B1.svg?url';
import MODEL_OPEN_CLOUDPSS_PCS_BAT_01_AVM_STD_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_PCS_BAT_01-AVM-STD-V1B1.svg?url';
import MODEL_OPEN_CLOUDPSS_SVG_01_AVM_STD_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_SVG_01-AVM-STD-V1B1.svg?url';
import MODEL_OPEN_CLOUDPSS_SVG_01_FDM_STD_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_SVG_01-FDM-STD-V1B1.svg?url';
import MODEL_CLOUDPSS_BLANK_OCTAVE_COMPONENTS_TRIGGER from './assets/MODEL_CLOUDPSS_BLANK_OCTAVE_COMPONENTS_TRIGGER.webp';
import MODEL_CLOUDPSS_BLANK_OCTAVE_COMPONENTS from './assets/MODEL_CLOUDPSS_BLANK_OCTAVE_COMPONENTS.webp';
import MODEL_OPEN_CLOUDPSS_IEEE_118_BUS_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_IEEE_118_BUS-V1B1.svg?url';
import MODEL_OPEN_CLOUDPSS_CSEE_FS_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_CSEE_FS-V1B1.svg?url';
import MODEL_OPEN_CLOUDPSS_CSEE_VS_VC_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_CSEE_VS_VC-V1B1.svg?url';
import MODEL_OPEN_CLOUDPSS_CSEE_PFO_CONTINUOUS_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_CSEE_PFO_CONTINUOUS-V1B1.svg?url';
import MODEL_OPEN_CLOUDPSS_CSEE_PFO_TEMPORARY_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_CSEE_PFO_TEMPORARY-V1B1.svg?url';
import MODEL_OPEN_CLOUDPSS_CSEE_VS_CLV_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_CSEE_VS_CLV-V1B1.svg?url';
import MODEL_OPEN_CLOUDPSS_CSEE_RAS_APERIODIC_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_CSEE_RAS_APERIODIC-V1B1.svg?url';
import MODEL_OPEN_CLOUDPSS_CSEE_RAS_PERIODIC_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_CSEE_RAS_PERIODIC-V1B1.svg?url';
import MODEL_CLOUDPSS_MMC_BENCHMARK from './assets/MODEL_CLOUDPSS_MMC_BENCHMARK.svg?url';
import MODEL_OPEN_CLOUDPSS_ZERO_CURRENT_PROTECTION_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_ZERO_CURRENT_PROTECTION-V1B1.svg?url';
import MODEL_OPEN_CLOUDPSS_DISTANCE_PROTECTION_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_DISTANCE_PROTECTION-V1B1.svg?url';
import MODEL_OPEN_CLOUDPSS_PILOT_PROTECTION_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_PILOT_PROTECTION-V1B1.svg?url';
import MODEL_OPEN_CLOUDPSS_CURRENT_PROTECTION_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_CURRENT_PROTECTION-V1B1.svg?url';
import MODEL_OPEN_CLOUDPSS_ZERO_VOLTAGE_PROTECTION_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_ZERO_VOLTAGE_PROTECTION-V1B1.svg?url';
import MODEL_OPEN_CLOUDPSS_COMPOUND_VOLTAGE_OVER_CURRENT_PROTECTION_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_COMPOUND_VOLTAGE_OVER_CURRENT_PROTECTION-V1B1.svg?url';
import MODEL_OPEN_CLOUDPSS_RECLOSE_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_RECLOSE-V1B1.svg?url';
import MODEL_OPEN_CLOUDPSS_HVDC_HYBRID_HI_FDM_STD_V1B3 from './assets/MODEL_OPEN-CLOUDPSS_HVDC_HYBRID_HI-FDM-STD-V1B3.svg?url';
import MODEL_OPEN_CLOUDPSS_HVDC_HYBRID_MT_FDM_STD_V1B3 from './assets/MODEL_OPEN-CLOUDPSS_HVDC_HYBRID_MT-FDM-STD-V1B3.svg?url';
import MODEL_OPEN_CLOUDPSS_HVDC_MMC_WF_FDM_STD_V1B2 from './assets/MODEL_OPEN-CLOUDPSS_HVDC_MMC_WF-FDM-STD-V1B2.svg?url';
import MODEL_OPEN_CLOUDPSS_HVDC_MMC_MT_FDM_STD_V1B2 from './assets/MODEL_OPEN-CLOUDPSS_HVDC_MMC_MT-FDM-STD-V1B2.svg?url';
import MODEL_OPEN_CLOUDPSS_HVDC_LCC_MT_FDM_STD_V1B2 from './assets/MODEL_OPEN-CLOUDPSS_HVDC_LCC_MT-FDM-STD-V1B2.svg?url';
import MODEL_OPEN_CLOUDPSS_HVDC_LCC_HI_FDM_STD_V1B2 from './assets/MODEL_OPEN-CLOUDPSS_HVDC_LCC_HI-FDM-STD-V1B2.svg?url';
import MODEL_OPEN_CLOUDPSS_HVDC_MMC_HI_FDM_STD_V1B2 from './assets/MODEL_OPEN-CLOUDPSS_HVDC_MMC_HI-FDM-STD-V1B2.svg?url';
import MODEL_OPEN_CLOUDPSS_HVDC_LCC_BP_FDM_STD_V1B2 from './assets/MODEL_OPEN-CLOUDPSS_HVDC_LCC_BP-FDM-STD-V1B2.svg?url';
import MODEL_OPEN_CLOUDPSS_HVDC_MMC_BP_FDM_STD_V1B2 from './assets/MODEL_OPEN-CLOUDPSS_HVDC_MMC_BP-FDM-STD-V1B2.svg?url';
import MODEL_OPEN_CLOUDPSS_HVDC_LCC_SP_FDM_STD_V1B2 from './assets/MODEL_OPEN-CLOUDPSS_HVDC_LCC_SP-FDM-STD-V1B2.svg?url';
import MODEL_OPEN_CLOUDPSS_HVDC_MMC_SP_FDM_STD_V1B2 from './assets/MODEL_OPEN-CLOUDPSS_HVDC_MMC_SP-FDM-STD-V1B2.svg?url';
import MODEL_OPEN_CLOUDPSS_PVS_01_AVM_STD_V1B2 from './assets/MODEL_OPEN-CLOUDPSS_PVS_01-AVM-STD-V1B2.svg?url';
import MODEL_OPEN_CLOUDPSS_PVS_01_FDM_STD_V1B2 from './assets/MODEL_OPEN-CLOUDPSS_PVS_01-FDM-STD-V1B2.svg?url';
import MODEL_OPEN_CLOUDPSS_WTG_DFIG_01_FDM_STD_V1B3 from './assets/MODEL_OPEN-CLOUDPSS_WTG_DFIG_01-FDM-STD-V1B3.svg?url';
import MODEL_OPEN_CLOUDPSS_WTG_DFIG_01_AVM_STD_V1B3 from './assets/MODEL_OPEN-CLOUDPSS_WTG_DFIG_01-AVM-STD-V1B3.svg?url';
import MODEL_OPEN_CLOUDPSS_WTG_PMSG_01_AVM_STD_V2B2 from './assets/MODEL_OPEN-CLOUDPSS_WTG_PMSG_01-AVM-STD-V2B2.svg?url';
import MODEL_OPEN_CLOUDPSS_WTG_PMSG_01_FDM_STD_V2B2 from './assets/MODEL_OPEN-CLOUDPSS_WTG_PMSG_01-FDM-STD-V2B2.svg?url';
import MODEL_OPEN_CLOUDPSS_IEEE_39_BUS_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_IEEE_39_BUS-V1B1.svg?url';
import MODEL_OPEN_CLOUDPSS_IEEE_30_BUS_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_IEEE_30_BUS-V1B1.svg?url';
import MODEL_OPEN_CLOUDPSS_IEEE_14_BUS_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_IEEE_14_BUS-V1B1.svg?url';
import MODEL_OPEN_CLOUDPSS_WSCC_9_BUS_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_WSCC_9_BUS-V1B1.svg?url';
import MODEL_OPEN_CLOUDPSS_KUNDUR_TWO_AREA_V1B1 from './assets/MODEL_OPEN-CLOUDPSS_KUNDUR_TWO_AREA-V1B1.svg?url';
import MODEL_CLOUDPSS_IEEE39_SSC_DEMO from './assets/MODEL_CLOUDPSS_IEEE39-SSC-DEMO.svg?url';
import MODEL_CLOUDPSS_SUBSTATIONCASE from './assets/MODEL_CLOUDPSS_SUBSTATIONCASE.svg?url';
import MODEL_CLOUDPSS_HVDC800 from './assets/MODEL_CLOUDPSS_HVDC800.svg?url';
import MODEL_CLOUDPSS_HVDC_PN_12 from './assets/MODEL_CLOUDPSS_HVDC_PN_12.svg?url';
import MODEL_CLOUDPSS_HVDC_PN_D12 from './assets/MODEL_CLOUDPSS_HVDC_PN_D12.svg?url';
import MODEL_CLOUDPSS_HVDC_P_D12 from './assets/MODEL_CLOUDPSS_HVDC_P_D12.svg?url';
import MODEL_CLOUDPSS_HVDC_P_12 from './assets/MODEL_CLOUDPSS_HVDC_P_12.svg?url';
import MODEL_CLOUDPSS_HLM from './assets/MODEL_CLOUDPSS_HLM.svg?url';
import MODEL_CLOUDPSS_HTMODULE from './assets/MODEL_CLOUDPSS_HTMODULE.svg?url';
import MODEL_CLOUDPSS_HBRIDGEMODULE from './assets/MODEL_CLOUDPSS_HBRIDGEMODULE.svg?url';
import MODEL_CLOUDPSS_HALFBRIDGEMODULE from './assets/MODEL_CLOUDPSS_HALFBRIDGEMODULE.svg?url';
import MODEL_CLOUDPSS_3HM from './assets/MODEL_CLOUDPSS_3HM.svg?url';
import MODEL_CLOUDPSS_DFIG_AVM from './assets/MODEL_CLOUDPSS_DFIG_AVM.svg?url';
import MODEL_CLOUDPSS_PV_AVERAGED_DETAILED from './assets/MODEL_CLOUDPSS_PV_AVERAGED_DETAILED.svg?url';
import MODEL_CLOUDPSS_PV_AVERAGED from './assets/MODEL_CLOUDPSS_PV_AVERAGED.svg?url';
import MODEL_CLOUDPSS_PV_DETAILED from './assets/MODEL_CLOUDPSS_PV_DETAILED.svg?url';
import MODEL_CLOUDPSS_BAT_AVERAGED_DETAILED from './assets/MODEL_CLOUDPSS_BAT_AVERAGED_DETAILED.svg?url';
import MODEL_CLOUDPSS_BAT_AVERAGED from './assets/MODEL_CLOUDPSS_BAT_AVERAGED.svg?url';
import MODEL_CLOUDPSS_BAT_DETAILED from './assets/MODEL_CLOUDPSS_BAT_DETAILED.svg?url';
import MODEL_CLOUDPSS_DC_MICROGRID from './assets/MODEL_CLOUDPSS_DC_MICROGRID.svg?url';
import MODEL_CLOUDPSS_NPCMODULE from './assets/MODEL_CLOUDPSS_NPCMODULE.svg?url';
import MODEL_CLOUDPSS_NSSTS from './assets/MODEL_CLOUDPSS_NSSTS.svg?url';
import MODEL_CLOUDPSS_B2BMODULE from './assets/MODEL_CLOUDPSS_B2BMODULE.svg?url';
import MODEL_CLOUDPSS_DC_MOTOR from './assets/MODEL_CLOUDPSS_DC_MOTOR.svg?url';
import MODEL_CLOUDPSS_ASYN_MOTOR from './assets/MODEL_CLOUDPSS_ASYN_MOTOR.svg?url';
import MODEL_CLOUDPSS_FESS from './assets/MODEL_CLOUDPSS_FESS.webp';
import Freq_Sweep_Analyzer from './assets/Freq-Sweep-Analyzer.webp';
import Green_Energy from './assets/Green-Energy.webp';
import System_Splitting from './assets/System-Splitting.webp';
import IES_with_Distributed_Heating from './assets/ies-with-distributed-heating.svg?url';
import IES_with_Centralized_Heating from './assets/ies-with-centralized-heating.svg?url';
import AC_DC_Hybrid_Distribution_System_With_Renewables from './assets/ac-dc-hybrid-distribution-system-with-renewables.webp';
import IES_Building from './assets/ies-building.webp';
import IES_CCHP from './assets/ies-cchp.webp';
import IES_Park from './assets/ies-park.webp';
import hours_8760 from './assets/hours-8760.webp';
import 跟网型储能变流器 from './assets/跟网型储能变流器-平均模型 - 电气主拓扑.svg?url';
import 构网型储能变流器 from './assets/构网型储能变流器-平均模型 - 电气主拓扑.svg?url';
import 跟网构网型并网变流器 from './assets/跟网_构网型并网变流器-平均模型 - 电气主拓扑.svg?url';

const TEMPLATE_PIC_DICT: Record<string, string> = {
    'SVG 01 型-标准封装模型-v1': MODEL_OPEN_CLOUDPSS_SVG_01_AVM_STDM_V1B1,
    '电池储能 01 型-标准封装模型-v1': MODEL_OPEN_CLOUDPSS_PCS_BAT_01_AVM_STDM_V1B1,
    '光伏发电 01 型-标准封装模型-v1': MODEL_OPEN_CLOUDPSS_PVS_01_AVM_STDM_V1B5,
    '双馈风机 01 型-标准封装模型-v1': MODEL_OPEN_CLOUDPSS_WTG_DFIG_01_AVM_STDM_V1B5,
    '直驱风机 01 型-标准封装模型-v2': MODEL_OPEN_CLOUDPSS_WTG_PMSG_01_AVM_STDM_V2B5,
    '10 机 39 节点标准测试系统': MODEL_CLOUDPSS_IEEE39,
    '3 机 9 节点标准测试系统': MODEL_CLOUDPSS_IEEE3,
    空白综合能源系统模型: MODEL_CLOUDPSS_BLANK_IESMODEL,
    空白电力系统元件: MODEL_CLOUDPSS_BLANK_COMPONENT,
    空白普通电力系统模型: MODEL_CLOUDPSS_BLANK_COMMON,
    空白简单电力系统模型: MODEL_CLOUDPSS_BLANK_SIMPLE,
    '电池储能 01 型-快速详细模型-标准模型-v1': MODEL_OPEN_CLOUDPSS_PCS_BAT_01_FDM_STD_V1B1,
    '电池储能 01 型-平均模型-标准模型-v1': MODEL_OPEN_CLOUDPSS_PCS_BAT_01_AVM_STD_V1B1,
    'SVG 01 型-平均模型-标准模型-v1': MODEL_OPEN_CLOUDPSS_SVG_01_AVM_STD_V1B1,
    'SVG 01 型-快速详细模型-标准模型-v1': MODEL_OPEN_CLOUDPSS_SVG_01_FDM_STD_V1B1,
    '空白 Octave 元件（外部触发式）': MODEL_CLOUDPSS_BLANK_OCTAVE_COMPONENTS_TRIGGER,
    '空白 Octave 元件': MODEL_CLOUDPSS_BLANK_OCTAVE_COMPONENTS,
    '118 节点测试系统': MODEL_OPEN_CLOUDPSS_IEEE_118_BUS_V1B1,
    'CSEE 标准算例-高/低频问题': MODEL_OPEN_CLOUDPSS_CSEE_FS_V1B1,
    'CSEE 标准算例-电压崩溃问题': MODEL_OPEN_CLOUDPSS_CSEE_VS_VC_V1B1,
    'CSEE 标准算例-稳态工频过电压': MODEL_OPEN_CLOUDPSS_CSEE_PFO_CONTINUOUS_V1B1,
    'CSEE 标准算例-暂时工频过电压': MODEL_OPEN_CLOUDPSS_CSEE_PFO_TEMPORARY_V1B1,
    'CSEE 标准算例-持续低电压问题': MODEL_OPEN_CLOUDPSS_CSEE_VS_CLV_V1B1,
    'CSEE 标准算例-功角失稳': MODEL_OPEN_CLOUDPSS_CSEE_RAS_APERIODIC_V1B1,
    'CSEE 标准算例-功角振荡': MODEL_OPEN_CLOUDPSS_CSEE_RAS_PERIODIC_V1B1,
    模块化多电平变流器及其控制系统: MODEL_CLOUDPSS_MMC_BENCHMARK,
    电力系统三段式零序电流保护基础案例: MODEL_OPEN_CLOUDPSS_ZERO_CURRENT_PROTECTION_V1B1,
    电力系统距离保护基础案例: MODEL_OPEN_CLOUDPSS_DISTANCE_PROTECTION_V1B1,
    电力系统线路纵联差动保护基础案例: MODEL_OPEN_CLOUDPSS_PILOT_PROTECTION_V1B1,
    电力系统三段式电流保护基础案例: MODEL_OPEN_CLOUDPSS_CURRENT_PROTECTION_V1B1,
    电力系统零序电压保护基础案例: MODEL_OPEN_CLOUDPSS_ZERO_VOLTAGE_PROTECTION_V1B1,
    电力系统复压过流保护基础案例: MODEL_OPEN_CLOUDPSS_COMPOUND_VOLTAGE_OVER_CURRENT_PROTECTION_V1B1,
    电力系统重合闸基础案例: MODEL_OPEN_CLOUDPSS_RECLOSE_V1B1,
    特高压混合分层直流输电系统: MODEL_OPEN_CLOUDPSS_HVDC_HYBRID_HI_FDM_STD_V1B3,
    混合多端直流输电系统: MODEL_OPEN_CLOUDPSS_HVDC_HYBRID_MT_FDM_STD_V1B3,
    海风孤岛送电柔直输电系统: MODEL_OPEN_CLOUDPSS_HVDC_MMC_WF_FDM_STD_V1B2,
    多端柔性直流输电系统: MODEL_OPEN_CLOUDPSS_HVDC_MMC_MT_FDM_STD_V1B2,
    多端常规直流输电系统: MODEL_OPEN_CLOUDPSS_HVDC_LCC_MT_FDM_STD_V1B2,
    特高压分层常规直流输电系统: MODEL_OPEN_CLOUDPSS_HVDC_LCC_HI_FDM_STD_V1B2,
    特高压分层柔性直流输电系统: MODEL_OPEN_CLOUDPSS_HVDC_MMC_HI_FDM_STD_V1B2,
    双极端对端常直输电系统: MODEL_OPEN_CLOUDPSS_HVDC_LCC_BP_FDM_STD_V1B2,
    双极端对端柔直输电系统: MODEL_OPEN_CLOUDPSS_HVDC_MMC_BP_FDM_STD_V1B2,
    '单极（伪双极）端对端常直输电系统': MODEL_OPEN_CLOUDPSS_HVDC_LCC_SP_FDM_STD_V1B2,
    '单极（伪双极）端对端柔直输电系统': MODEL_OPEN_CLOUDPSS_HVDC_MMC_SP_FDM_STD_V1B2,
    '光伏发电 01 型-平均模型-标准模型-v1': MODEL_OPEN_CLOUDPSS_PVS_01_AVM_STD_V1B2,
    '光伏发电 01 型-快速详细模型-标准模型-v1': MODEL_OPEN_CLOUDPSS_PVS_01_FDM_STD_V1B2,
    '双馈风机 01 型-快速详细模型-标准模型-v1': MODEL_OPEN_CLOUDPSS_WTG_DFIG_01_FDM_STD_V1B3,
    '双馈风机 01 型-平均模型-标准模型-v1': MODEL_OPEN_CLOUDPSS_WTG_DFIG_01_AVM_STD_V1B3,
    '直驱风机 01 型-平均模型-标准模型-v2': MODEL_OPEN_CLOUDPSS_WTG_PMSG_01_AVM_STD_V2B2,
    '直驱风机 01 型-快速详细模型-标准模型-v2': MODEL_OPEN_CLOUDPSS_WTG_PMSG_01_FDM_STD_V2B2,
    '10 机 39 节点测试系统': MODEL_OPEN_CLOUDPSS_IEEE_39_BUS_V1B1,
    '30 节点测试系统': MODEL_OPEN_CLOUDPSS_IEEE_30_BUS_V1B1,
    '5 机 14 节点测试系统': MODEL_OPEN_CLOUDPSS_IEEE_14_BUS_V1B1,
    '3 机 9 节点测试系统': MODEL_OPEN_CLOUDPSS_WSCC_9_BUS_V1B1,
    '4 机 2 区域测试系统': MODEL_OPEN_CLOUDPSS_KUNDUR_TWO_AREA_V1B1,
    '10 机 39 节点标准系统安控策略案例': MODEL_CLOUDPSS_IEEE39_SSC_DEMO,
    '110kV变电站一、二次系统': MODEL_CLOUDPSS_SUBSTATIONCASE,
    高压直流输电系统: MODEL_CLOUDPSS_HVDC800,
    '双极 12 脉动': MODEL_CLOUDPSS_HVDC_PN_12,
    '双极双 12 脉动': MODEL_CLOUDPSS_HVDC_PN_D12,
    '单极双 12 脉动': MODEL_CLOUDPSS_HVDC_P_D12,
    '单极 12 脉动': MODEL_CLOUDPSS_HVDC_P_12,
    '单相 H 桥变流器(带电感)': MODEL_CLOUDPSS_HLM,
    '单相 H 桥变流器(带变压器)': MODEL_CLOUDPSS_HTMODULE,
    '单相 H 桥变流器': MODEL_CLOUDPSS_HBRIDGEMODULE,
    '双向 DC/DC 变流器': MODEL_CLOUDPSS_HALFBRIDGEMODULE,
    '三相 H 桥变流器': MODEL_CLOUDPSS_3HM,
    '双馈电机双 PWM 平均化控制': MODEL_CLOUDPSS_DFIG_AVM,
    '光伏详细化/平均化模型对比': MODEL_CLOUDPSS_PV_AVERAGED_DETAILED,
    光伏平均化模型: MODEL_CLOUDPSS_PV_AVERAGED,
    光伏详细化模型: MODEL_CLOUDPSS_PV_DETAILED,
    '储能详细化/平均化模型对比': MODEL_CLOUDPSS_BAT_AVERAGED_DETAILED,
    储能平均化模型: MODEL_CLOUDPSS_BAT_AVERAGED,
    储能详细化模型: MODEL_CLOUDPSS_BAT_DETAILED,
    直流微电网系统: MODEL_CLOUDPSS_DC_MICROGRID,
    中点钳位三电平半桥变流器: MODEL_CLOUDPSS_NPCMODULE,
    多模块固态变压器: MODEL_CLOUDPSS_NSSTS,
    单相背靠背变流器: MODEL_CLOUDPSS_B2BMODULE,
    直流电机驱动: MODEL_CLOUDPSS_DC_MOTOR,
    异步电机矢量控制: MODEL_CLOUDPSS_ASYN_MOTOR,
    飞轮储能系统: MODEL_CLOUDPSS_FESS,
    扫频分析应用: Freq_Sweep_Analyzer,
    绿电分析系统: Green_Energy,
    解列计算系统: System_Splitting,
    分布式供热的综合能源系统: IES_with_Distributed_Heating,
    集中式供热的综合能源系统: IES_with_Centralized_Heating,
    风光储交直流配电网: AC_DC_Hybrid_Distribution_System_With_Renewables,
    楼宇型综合能源系统: IES_Building,
    冷热电三联供系统: IES_CCHP,
    综合能源系统园区展示项目: IES_Park,
    '风光储项目8760h 规划优化': hours_8760,
    综合能源系统园区项目: IES_Park,
    '跟网型储能变流器-平均模型-v1': 跟网型储能变流器,
    '构网型储能变流器-平均模型-v1': 构网型储能变流器,
    '跟网/构网型并网变流器-平均模型-v1': 跟网构网型并网变流器,
};

export { TEMPLATE_PIC_DICT };
