name: build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install
        uses: wyvox/action-setup-pnpm@v3
        with:
          pnpm-version: 8
      - name: Optimize
        run: pnpm optimize
      - name: Build
        env:
          DOCS_BASE_URL: /${{ github.event.repository.name }}/
        run: pnpm build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build
          force_orphan: true
          enable_jekyll: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
