name: release

on:
  push:
    tags: ['*']

jobs:
  build-standalone:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install
        uses: bahmutov/npm-install@v1
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3 | sed -e 's/\./_/g')
      - name: Build for standalone
        run: |
          pnpm build:standalone
          rm -f dist/stats.json dist/*.map
          sed -i "s/__VERSION__/$(echo ${{ steps.get_version.outputs.VERSION }} | cut -c 2- | sed -e 's/_/./g' | sed -e 's/-/~/g')/g" deb/DEBIAN/control
          sed -i "s/__INSTALLED_SIZE__/$(du -sk dist | cut -f 1)/g" deb/DEBIAN/control
          cat deb/DEBIAN/control
          cp -a dist/. deb/usr/share/cloudpss/static/docs/
          dpkg-deb --build --root-owner-group deb .
          ls -l *.deb
      - name: Upload Release Asset
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: '*.deb'
          prerelease: ${{ contains(github.event.ref, '-') }}
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-public:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install
        uses: NullVoxPopuli/action-setup-pnpm@v2
        with:
          node-version: lts/*
          pnpm-version: 8
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3 | sed -e 's/\./_/g')
      - name: Build for docs.cloudpss.net
        run: |
          pnpm build:main
          rm -f dist/stats.json
          tar -cJf dist.tar.xz -C ./dist .
          ls -l dist.tar.xz
      - name: Upload Release Asset
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: dist.tar.xz
          prerelease: ${{ contains(github.event.ref, '-') }}
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.DC_HOST }}
          port: ${{ secrets.DC_PORT }}
          user: ${{ secrets.DC_USER }}
          key: ${{ secrets.DC_KEY }}
          connect_timeout: 600s
          first_ssh: |
            rm -f /root/docs/dist.tar.xz
          scp: |
            './dist.tar.xz' => /root/docs/
          last_ssh: |
            source /root/.profile
            rm -rf /root/docs/${{ steps.get_version.outputs.VERSION }}
            mkdir -p /root/docs/${{ steps.get_version.outputs.VERSION }}
            tar -xJf /root/docs/dist.tar.xz -C /root/docs/${{ steps.get_version.outputs.VERSION }}
            gzipper c --exclude map,jpeg,jpg,png,gif,ico,mp3,mp4,mkv --gzip-level 9 --remove-larger /root/docs/${{ steps.get_version.outputs.VERSION }}
            gzipper c --exclude map,jpeg,jpg,png,gif,ico,mp3,mp4,mkv --brotli --remove-larger /root/docs/${{ steps.get_version.outputs.VERSION }}
            rm -f /root/docs/latest
            ln -s /root/docs/${{ steps.get_version.outputs.VERSION }} /root/docs/latest
            rm -f /root/docs/dist.tar.xz
            systemctl reload caddy
            ls -l /root/docs/
      - name: Release
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        if: ${{ !contains(steps.get_version.outputs.VERSION, '-') }}
        with:
          host: ${{ secrets.DC_HOST }}
          port: ${{ secrets.DC_PORT }}
          user: ${{ secrets.DC_USER }}
          key: ${{ secrets.DC_KEY }}
          connect_timeout: 600s
          first_ssh: |
            rm -f /root/docs/release
            ln -s /root/docs/${{ steps.get_version.outputs.VERSION }} /root/docs/release
            systemctl reload caddy
            ls -l
