name: release

on:
  push:
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.3
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - name: Install
        uses: bahmutov/npm-install@v1.1.0
      - name: Build
        run: yarn build -c production
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.DC_HOST }}
          port: ${{ secrets.DC_PORT }}
          user: ${{ secrets.DC_USER }}
          key: ${{ secrets.DC_KEY }}
          connect_timeout: 60s
          first_ssh: |
            rm -rf /root/docs/${{ steps.get_version.outputs.VERSION }}
            mkdir -p /root/docs/${{ steps.get_version.outputs.VERSION }}
          scp: |
            './dist/*' => /root/docs/${{ steps.get_version.outputs.VERSION }}
          last_ssh: |
            rm -f /root/docs/latest
            ln -s /root/docs/${{ steps.get_version.outputs.VERSION }} /root/docs/latest
            service nginx reload
